sonar.projectKey=codemastersolutions_commitzero_eb012d27-7d59-454a-907f-b31e016f7358
sonar.projectName=CommitZero
sonar.sourceEncoding=UTF-8

sonar.sources=src,scripts
sonar.tests=test
sonar.test.inclusions=test/**/*
sonar.exclusions=dist/**,coverage/**,docs/**,tmp/**,.commitzero/**,**/*.html

sonar.typescript.tsconfigPaths=tsconfig.esm.json,tsconfig.cjs.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.scanner.skipNodeProvisioning=true
