name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Tipo de incremento de versão'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Verificar READMEs
        run: npm run verify:readmes

      - name: Lint
        run: npm run lint

      - name: Executar testes
        run: npm test

      - name: Build
        run: npm run build

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Incrementar versão
        id: bump
        run: |
          npm version ${{ inputs.bump }} -m "chore(release): %s"
          echo "version=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Push de mudanças e tags
        run: |
          git push --follow-tags

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.bump.outputs.version }}"
          name: "Release v${{ steps.bump.outputs.version }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar no npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}